@documentid = HHi05T3tabPfzCNijYqPd 
GET http://localhost:5000/find HTTP/1.1
###
GET http://localhost:5000/find?collectionid=noexistedyouknow HTTP/1.1
###
GET http://localhost:5000/find?collectioniderror={{documentid}} HTTP/1.1
###
GET http://localhost:5000/find?cwoefe=hVfwe&jofw=fowe HTTP/1.1
###
GET https://3ab8-190-14-129-217.ngrok.io/find?collectionid={{documentid}} HTTP/1.1

###
GET http://localhost:5000/find?collectionid={{documentid}} HTTP/1.1
###
GET http://localhost:5000/find?collectionid={{documentid}}&id=Sjewf9 HTTP/1.1