@collectionid = hY5sSsJYoThGyiVV7QHRr 
@documentid = Hz5POr
GET http://localhost:5000/find HTTP/1.1
###
GET http://localhost:5000/find?collectionid=noexistedyouknow HTTP/1.1
###
GET http://localhost:5000/find?collectioniderror={{documentid}} HTTP/1.1
###
GET http://localhost:5000/find?cwoefe=hVfwe&jofw=fowe HTTP/1.1
###
GET http://localhost:5000/find?collectionid={{collectionid}} HTTP/1.1
Content-Type: application/json

{
    "_id": "{{documentid}}"
}
###
GET http://localhost:5000/find?collectionid={{collectionid}}&id={{documentid}} HTTP/1.1