
name: Deploy to GCP server

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      
      - run: which fnm
      
      - run: which node
      
      - run: which npm
      
      - run: which pnpm
      
      # - run: export PNPM_HOME="/home/shockerovip/.local/share/pnpm" & export PATH="$PNPM_HOME:$PATH"
      


      # - run: pnpm install pm2 -g

      - name: Display the path
        run: echo $PATH
        shell: bash
