
name: Deploy to GCP server

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      
      # - name: Install dependencies
      - run: export PATH=/home/shockerovip/.fnm:$PATH
      - run: eval "`fnm env`"
      - run: eval "$(fnm env --use-on-cd)"
      - run: echo $(node -v)
      #  run: ~/.local/share/pnpm/pnpm install

      - run: pm2 restart micro-db2
      # - name: Restart pm2
      # run: /home/shockerovip/.local/share/pnpm/pm2 restart micro-db
      # run: /home/shockerovip/.local/share/pnpm/pm2 restart micro-db
