
name: Deploy to GCP server

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      
      - run: pwd
      
      - run: echo $USER
      
      - name: Install dependencies
        run: /home/shockerovip/.local/share/pnpm/pnpm install
      
      - name: Restart pm2
        run: pm2 restart micro-db
