
name: Deploy to GCP server

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      
      # - name: Install dependencies
      #  run: ~/.local/share/pnpm/pnpm install
      
      - run: eval "$(~/.fnm/fnm env)"
      
      - run: command -v fnm
      
      - run: command -v node
      
      - run: command -v pnpm
      
      - run: command -v pm2
      #- run: pm2 restart micro-db
      # - name: Restart pm2
      # run: /home/shockerovip/.local/share/pnpm/pm2 restart micro-db
      # run: /home/shockerovip/.local/share/pnpm/pm2 restart micro-db
