
name: Deploy to GCP server

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - run: command -v node
      
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      
      - name: install pm2
        run: npm install pm2 -g
      
     # - run: if [ -x "$(command -v pm2)" ]; then pm2 restart micro-db ; else pnpm install pm2 -g & pm2 start main.mjs --name=micro-db ; fi
      
      # - name: Install dependencies
      # - run: export PATH=/home/shockerovip/.fnm:$PATH
      # - run: eval "`fnm env`"
      # - run: eval "$(fnm env --use-on-cd)"
      # - run: echo $(node -v)
      #  run: ~/.local/share/pnpm/pnpm install

      # - run: pm2 restart micro-db2
      # - name: Restart pm2
      # run: /home/shockerovip/.local/share/pnpm/pm2 restart micro-db
      # run: /home/shockerovip/.local/share/pnpm/pm2 restart micro-db
