
name: Deploy to GCP server

defaults:
  run:
    shell: bash -eo pipefail {0}

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      
      - run: pnpm install
      
      - run: pm2 restart micro-db
