
name: Deploy to GCP server

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: ~/.local/share/pnpm/pnpm install
      
      - run: ls /home/shockerovip/.local/share/pnpm & /home/shockerovip/.local/share/pnpm/pm2 restart micro-db
      # - name: Restart pm2
      # run: /home/shockerovip/.local/share/pnpm/pm2 restart micro-db
      # run: /home/shockerovip/.local/share/pnpm/pm2 restart micro-db
