#workflow name
name: "simple workflow pm2 configuration"

defaults:
  run:
    shell: bash

#event, trigger action that running our Jobs.
on: [workflow_dispatch]

jobs:
  pm2-configuration:
    #runner, This job will be running in runner with Ubuntu Server latest version.
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3 
      - run: bash install.sh
      - run: source /home/$USER/.bashrc
