name: "testnode"

defaults:
  run:
    shell: bash --login

#event, trigger action that running our Jobs.
on: [workflow_dispatch]

jobs:
  pm2-configuration:
    #runner, This job will be running in runner with Ubuntu Server latest version.
    runs-on: self-hosted
    steps:
      - name: Display the path
        run: echo $PATH
      - run: command -v node
